title: "Blockchain Technology and Cybersecurity (BTC) Lab"
description: "BTC Lab @ University of Guelph"
author: "Xiaodong Lin"
baseurl: ""
url: "http://BtclabGuelph.github.io/"

twitter_username: btclabguelph
github_username: BtclabGuelph
source_url: "https://github.com/BtclabGuelph/BtclabGuelph.github.io"

# Build settings
markdown: kramdown
sass:
  compressed: true
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - build.sh
  - Rakefile
  - spectre
paginate: 5
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->
defaults:
  - scope:
      path: "blog/_posts"
    values:
      permalink: /:year/:month/:day/:title.html
  - scope:
      path: "talks/_posts"
    values:
      permalink: /talks/:title.html
